import { Button, TabWidget, TextEdit, ListView, StandardListView, VerticalBox, HorizontalBox, ScrollView, ComboBox } from "std-widgets.slint";

export component MainWindow inherits Window  {
    in property <[string]> use_cases;
    callback start_use_case(string);
    in-out property <string> output;
    callback remove_unwanted_connections();

    in-out property <[string]> jack_sources;
    in-out property <int> jack_selected;
    callback jack_source_clicked(int);

    in-out property <[StandardListViewItem]> autio_programs;
    in-out property <int> program_selected;
    callback program_selectiion_changed(int);

    in-out property <string> edit_program_name;
    callback program_name_changed();
    in-out property <string> edit_command_name;
    callback command_name_changed();
    in-out property <string> edit_start_params;
    callback start_params_changed();
    callback start_app();

    in-out property <[StandardListViewItem]> jack_connections;
    in-out property <int> Jack_connection_selected;
    callback jack_connection_changed(int);
    callback jack_connection_add();

    in-out property <[string]> jack_filters;
    in-out property <string> jack_filter;
    callback jack_filter_changed();
    in-out property <string> jack_source;
    callback jack_source_changed();
    in-out property <string> jack_target;
    callback jack_target_changed();
    in-out property <string> jack_search;
    callback jack_search_changed();
    callback jack_connect();

    callback jack_connection_remove();

    in-out property <[string]> jack_targets;
    in-out property <int> jack_target_selected;
    callback jack_target_clicked(int);
    callback jack_target_reinit();

    callback save_settings();
    callback add_program();
    callback remove_program();

    title: "Audio-Programmsteuerung";

    icon: @image-url("icon.png");

    TabWidget {
        vertical-stretch: 1;
        Tab {
            title: "Programm";

            VerticalLayout {

                for use_case in use_cases : Button {
                    text: use-case;
                    horizontal-stretch: 1;
                    clicked => {
                        root.output = "Starte " + use-case;
                        root.start_use_case(use-case);
                    }
                }

                Text {
                    vertical-stretch: 1;
                    text: root.output;
                    wrap: word-wrap;
                }

                Button {
                    text: "Entferne unerwünschte Verbindungen";
                    horizontal-stretch: 1;
                    clicked => {
                        root.output = "Entferne unerwünschte Verbindungen";
                        root.remove_unwanted_connections();
                    }
                }
            }
        }

        Tab {
            title: "Einstellungen";

            VerticalLayout {
                HorizontalLayout {

                    VerticalLayout {
                        
                        StandardListView {
                            model: root.autio_programs;
                            current-item <=> root.program_selected;
                            current-item-changed => { root.program_selectiion_changed(self.current-item); }
                        }

                        // Trenner
                        Rectangle {
                            height: 1px;
                            background: #000;
                            horizontal-stretch: 1;
                        }

                        TextEdit {
                            text <=> root.edit_program_name;
                            placeholder-text: "Programmname";
                            edited => { root.program_name_changed(); }
                        }
                        TextEdit {
                            text <=> root.edit_command_name;
                            placeholder-text: "Kommando";
                            edited(text) => { root.command_name_changed(); }
                        }
                        TextEdit {
                            text <=> root.edit_start_params;
                            placeholder-text: "Startparameter (mit Leerzeichen getrennt)";
                            edited(text) => { root.start_params_changed(); }
                        }
                        Button {
                            text: "Starten";
                            horizontal-stretch: 1;
                            clicked => { root.start_app(); }
                        }
                        
                        StandardListView {
                            model: root.jack_connections;
                            current-item <=> root.Jack_connection_selected;
                            current-item-changed => { root.jack_connection_changed(self.current-item); }
                        }

                        HorizontalBox {
                            Button {
                                text: "Hinzufügen";
                                horizontal-stretch: 1;
                                clicked => { root.jack_connection_add(); }
                            }
                            Button {
                                text: "Entfernen";
                                horizontal-stretch: 1;
                                clicked => { root.jack_connection_remove(); }
                            }
                        }

                    }


                    VerticalLayout {

                        VerticalBox {

                            ComboBox {
                                model: root.jack_filters;
                                selected => {
                                    root.jack_filter = self.current-value;
                                    root.jack_filter_changed();
                                }
                            }
                            TextEdit {
                                text <=> root.jack_filter;
                                placeholder-text: "Filter";
                                edited(text) => { root.jack_filter_changed(); }
                            }
                            
                            ComboBox {
                                model: root.jack_sources;
                                current-index <=> root.jack_selected;
                                selected => {
                                    root.jack_source_clicked(self.current-index);
                                }
                            }

                            HorizontalBox {
                                VerticalBox {
                                    Button {
                                        text: ">";
                                        clicked => {
                                            root.jack_source = root.jack_sources[root.jack_selected];
                                            root.jack_source_changed();
                                        }
                                    }
                                }
                                TextEdit {
                                    text <=> root.jack_source;
                                    placeholder-text: "Quelle";
                                    edited(text) => { root.jack_source_changed(); }
                                }
                                
                            }
                            

                            ComboBox {
                                model: root.jack_targets;
                                current-index <=> root.jack_target_selected;
                                selected => {
                                    root.jack_target_clicked(self.current-index);
                                }
                            }
                            HorizontalBox {
                                VerticalBox {
                                    Button {
                                        text: ">";
                                        clicked => {
                                            root.jack_target = root.jack_targets[root.jack_target_selected];
                                            root.jack_target_changed();
                                        }
                                    }
                                }
                                TextEdit {
                                    text <=> root.jack_target;
                                    placeholder-text: "Ziel";
                                    edited(text) => { root.jack_target_changed(); }
                                }

                            }
                            TextEdit {
                                text <=> root.jack_search;
                                placeholder-text: "Suche";
                                edited(text) => { root.jack_search_changed(); }
                            }

                            Button {
                                text: "Verbinden";
                                horizontal-stretch: 1;
                                clicked => { root.jack_connect(); }
                            }

                            // Trenner
                            Rectangle {
                                height: 1px;
                                background: #000;
                                horizontal-stretch: 1;
                            }

                            Button {
                                text: "Audiogeräte aktualisieren";
                                horizontal-stretch: 1;
                                clicked => { root.jack_target_reinit(); }
                            }
                        }
                    }
                }
        
                HorizontalBox {
                    height: 40px;
                    horizontal-stretch: 0;
                    Button {
                        text: "Neu";
                        clicked => { root.add_program(); }
                    }
                    Button {
                        text: "Löschen";
                        clicked => { root.remove_program(); }
                    }
                    Button {
                        text: "Speichern";
                        clicked => { root.save_settings(); }
                    }
                }
            }
        }
    }
}