name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y libfontconfig-dev libfreetype6-dev
    - name: Build
      run: cargo build --release

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: jackstreamingmanager
        path: target/release/jackstreamingmanager
